use_frameworks!

platform :ios, '13.0'

target 'KommunicateCore-iOS-SDK_Example' do
  pod 'KommunicateCore-iOS-SDK', :path => '../'

  target 'KommunicateCore-iOS-SDK_Tests' do
    inherit! :search_paths

    
  end
end
