name: iOS Linter Build Check Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1.0'

      - name: Run Linter Check
        run: |
          pod lib lint --allow-warnings

      - name: Debug Environment Variables (Optional)
        run: echo "Environment variables set successfully."

      - name: Post Test Results to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `## iOS Automation Test Results\nCongratulations Linter Check Passed! 🎉`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
